version: '2'

services:
  traefik:
    image: traefik
    ports:
      # only expose https to outside world
      - "443:443"   # SSL
    expose:
      # traefik dashboard port
      - 8080
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host:traefik.keops.io"
      # get md5 from htpasswd or http://www.htaccesstools.com/htpasswd-generator/
      # and then double all $ to $$ to avoid docker-compose 
      traefik.frontend.auth.basic: "admin:$$apr1$$hq9tfroy$$nItMMo8rNqXJwPYiWejkh."
      traefik.port: 8080
   volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - /data/traefik/traefik.toml:/traefik.toml
    restart: "always"
    
   volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - /data/traefik/traefik.toml:/traefik.toml
      - /data/traefik/acme.json:/acme.json
    restart: "always"