version: '3.7'
services:
  traefik:
    image: traefik:cantal
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik.toml:/etc/traefik/traefik.toml:ro
      - acme.json:/acme.json
    networks:
      - web

networks:
  web:
    external: true
