version: '3.7'
services:
  traefik:
    image: traefik:v1.7.16
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/traefik/traefik.toml:/traefik.toml
      - ./conf/traefik/acme.json:/acme.json
    networks:
      - web

networks:
  web:
    driver: bridge
