[log]
  level = "INFO"
  format = "common"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[api]

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  # watch = true
  # exposedByDefault = true
  # swarmMode = false
[providers.file]
  filename = "/etc/traefik/traefik_dynamic.toml"
  watch = true

[certificatesResolvers.letsencrypt.acme]
  email = "admin@keops.io"
  storage = "acme.json"
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  keyType = "EC256"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "http"
