[global]
  sendAnonymousUsage = false

[log]
  level = "WARNING"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[api]
  dashboard = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"

# [certificatesResolvers.letsencrypt.acme]
#   email = "admin@keops.io"
#   storage = "acme.json"
#   caServer = "https://acme-v02.api.letsencrypt.org/directory"
#   keyType = "EC256"
#   [certificatesResolvers.letsencrypt.acme.httpChallenge]
#     entryPoint = "http"
