[global]
  sendAnonymousUsage = false

[log]
  level = "WARNING"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = true
    swarmMode = false

[entryPoints]
  [entryPoints.insecure]
  address = ":80"

  [entryPoints.secure]
  address = ":443"

[api]


[certificatesResolvers.letsencrypt.acme]
  email = "admin@keops.io"
  storage = "acme.json"
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  keyType = "EC256"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "http"
