debug = false

defaultEntryPoints = ["https","http"]

# The syntax is somewhat esoteric IMHO so this is mostly copy-paste
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik.keops.io"
watch = true
exposedbydefault = false

[acme]
email = "admin@keops.io"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
[acme.httpChallenge]
entryPoint = "http"

[[acme.domains]]
  main = "statik.keops.io"

# Enable web configuration backend
[web]

# Web administration port, proxied in docker-compose.yml
address = ":8080"
