[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[api]

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"

[certificatesResolvers.keops.acme]
  email = "admin@keops.io"
  storage = "acme.json"
  [certificatesResolvers.keops.acme.httpChallenge]
    entryPoint = "http"
